server:
  port: 18080 # 客户端专用测试端口

mim:
  client:
    test:
      username: shuangshu
      password: 12345
      host: localhost
      port: 8080
      name: mim-client-test

# 日志设置
logging:
  level:
    com.mdc.mim: info