/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.mdc.mim.user;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.15.0)", date = "2024-07-06")
public class User implements org.apache.thrift.TBase<User, User._Fields>, java.io.Serializable, Cloneable, Comparable<User> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("User");

  private static final org.apache.thrift.protocol.TField UID_FIELD_DESC = new org.apache.thrift.protocol.TField("Uid", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField USER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("UserName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PASSWD_MD5_FIELD_DESC = new org.apache.thrift.protocol.TField("PasswdMd5", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField NICK_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("NickName", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField REGISTER_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("RegisterDate", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new UserStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new UserTupleSchemeFactory();

  public long Uid; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String UserName; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String PasswdMd5; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String NickName; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String RegisterDate; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    UID((short)1, "Uid"),
    USER_NAME((short)2, "UserName"),
    PASSWD_MD5((short)3, "PasswdMd5"),
    NICK_NAME((short)4, "NickName"),
    REGISTER_DATE((short)5, "RegisterDate");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // UID
          return UID;
        case 2: // USER_NAME
          return USER_NAME;
        case 3: // PASSWD_MD5
          return PASSWD_MD5;
        case 4: // NICK_NAME
          return NICK_NAME;
        case 5: // REGISTER_DATE
          return REGISTER_DATE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __UID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.UID,_Fields.USER_NAME,_Fields.PASSWD_MD5,_Fields.NICK_NAME,_Fields.REGISTER_DATE};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.UID, new org.apache.thrift.meta_data.FieldMetaData("Uid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.USER_NAME, new org.apache.thrift.meta_data.FieldMetaData("UserName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PASSWD_MD5, new org.apache.thrift.meta_data.FieldMetaData("PasswdMd5", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NICK_NAME, new org.apache.thrift.meta_data.FieldMetaData("NickName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REGISTER_DATE, new org.apache.thrift.meta_data.FieldMetaData("RegisterDate", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(User.class, metaDataMap);
  }

  public User() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public User(User other) {
    __isset_bitfield = other.__isset_bitfield;
    this.Uid = other.Uid;
    if (other.isSetUserName()) {
      this.UserName = other.UserName;
    }
    if (other.isSetPasswdMd5()) {
      this.PasswdMd5 = other.PasswdMd5;
    }
    if (other.isSetNickName()) {
      this.NickName = other.NickName;
    }
    if (other.isSetRegisterDate()) {
      this.RegisterDate = other.RegisterDate;
    }
  }

  public User deepCopy() {
    return new User(this);
  }

  @Override
  public void clear() {
    setUidIsSet(false);
    this.Uid = 0;
    this.UserName = null;
    this.PasswdMd5 = null;
    this.NickName = null;
    this.RegisterDate = null;
  }

  public long getUid() {
    return this.Uid;
  }

  public User setUid(long Uid) {
    this.Uid = Uid;
    setUidIsSet(true);
    return this;
  }

  public void unsetUid() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __UID_ISSET_ID);
  }

  /** Returns true if field Uid is set (has been assigned a value) and false otherwise */
  public boolean isSetUid() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __UID_ISSET_ID);
  }

  public void setUidIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __UID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getUserName() {
    return this.UserName;
  }

  public User setUserName(@org.apache.thrift.annotation.Nullable java.lang.String UserName) {
    this.UserName = UserName;
    return this;
  }

  public void unsetUserName() {
    this.UserName = null;
  }

  /** Returns true if field UserName is set (has been assigned a value) and false otherwise */
  public boolean isSetUserName() {
    return this.UserName != null;
  }

  public void setUserNameIsSet(boolean value) {
    if (!value) {
      this.UserName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPasswdMd5() {
    return this.PasswdMd5;
  }

  public User setPasswdMd5(@org.apache.thrift.annotation.Nullable java.lang.String PasswdMd5) {
    this.PasswdMd5 = PasswdMd5;
    return this;
  }

  public void unsetPasswdMd5() {
    this.PasswdMd5 = null;
  }

  /** Returns true if field PasswdMd5 is set (has been assigned a value) and false otherwise */
  public boolean isSetPasswdMd5() {
    return this.PasswdMd5 != null;
  }

  public void setPasswdMd5IsSet(boolean value) {
    if (!value) {
      this.PasswdMd5 = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getNickName() {
    return this.NickName;
  }

  public User setNickName(@org.apache.thrift.annotation.Nullable java.lang.String NickName) {
    this.NickName = NickName;
    return this;
  }

  public void unsetNickName() {
    this.NickName = null;
  }

  /** Returns true if field NickName is set (has been assigned a value) and false otherwise */
  public boolean isSetNickName() {
    return this.NickName != null;
  }

  public void setNickNameIsSet(boolean value) {
    if (!value) {
      this.NickName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getRegisterDate() {
    return this.RegisterDate;
  }

  public User setRegisterDate(@org.apache.thrift.annotation.Nullable java.lang.String RegisterDate) {
    this.RegisterDate = RegisterDate;
    return this;
  }

  public void unsetRegisterDate() {
    this.RegisterDate = null;
  }

  /** Returns true if field RegisterDate is set (has been assigned a value) and false otherwise */
  public boolean isSetRegisterDate() {
    return this.RegisterDate != null;
  }

  public void setRegisterDateIsSet(boolean value) {
    if (!value) {
      this.RegisterDate = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case UID:
      if (value == null) {
        unsetUid();
      } else {
        setUid((java.lang.Long)value);
      }
      break;

    case USER_NAME:
      if (value == null) {
        unsetUserName();
      } else {
        setUserName((java.lang.String)value);
      }
      break;

    case PASSWD_MD5:
      if (value == null) {
        unsetPasswdMd5();
      } else {
        setPasswdMd5((java.lang.String)value);
      }
      break;

    case NICK_NAME:
      if (value == null) {
        unsetNickName();
      } else {
        setNickName((java.lang.String)value);
      }
      break;

    case REGISTER_DATE:
      if (value == null) {
        unsetRegisterDate();
      } else {
        setRegisterDate((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case UID:
      return getUid();

    case USER_NAME:
      return getUserName();

    case PASSWD_MD5:
      return getPasswdMd5();

    case NICK_NAME:
      return getNickName();

    case REGISTER_DATE:
      return getRegisterDate();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case UID:
      return isSetUid();
    case USER_NAME:
      return isSetUserName();
    case PASSWD_MD5:
      return isSetPasswdMd5();
    case NICK_NAME:
      return isSetNickName();
    case REGISTER_DATE:
      return isSetRegisterDate();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof User)
      return this.equals((User)that);
    return false;
  }

  public boolean equals(User that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_Uid = true && this.isSetUid();
    boolean that_present_Uid = true && that.isSetUid();
    if (this_present_Uid || that_present_Uid) {
      if (!(this_present_Uid && that_present_Uid))
        return false;
      if (this.Uid != that.Uid)
        return false;
    }

    boolean this_present_UserName = true && this.isSetUserName();
    boolean that_present_UserName = true && that.isSetUserName();
    if (this_present_UserName || that_present_UserName) {
      if (!(this_present_UserName && that_present_UserName))
        return false;
      if (!this.UserName.equals(that.UserName))
        return false;
    }

    boolean this_present_PasswdMd5 = true && this.isSetPasswdMd5();
    boolean that_present_PasswdMd5 = true && that.isSetPasswdMd5();
    if (this_present_PasswdMd5 || that_present_PasswdMd5) {
      if (!(this_present_PasswdMd5 && that_present_PasswdMd5))
        return false;
      if (!this.PasswdMd5.equals(that.PasswdMd5))
        return false;
    }

    boolean this_present_NickName = true && this.isSetNickName();
    boolean that_present_NickName = true && that.isSetNickName();
    if (this_present_NickName || that_present_NickName) {
      if (!(this_present_NickName && that_present_NickName))
        return false;
      if (!this.NickName.equals(that.NickName))
        return false;
    }

    boolean this_present_RegisterDate = true && this.isSetRegisterDate();
    boolean that_present_RegisterDate = true && that.isSetRegisterDate();
    if (this_present_RegisterDate || that_present_RegisterDate) {
      if (!(this_present_RegisterDate && that_present_RegisterDate))
        return false;
      if (!this.RegisterDate.equals(that.RegisterDate))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetUid()) ? 131071 : 524287);
    if (isSetUid())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(Uid);

    hashCode = hashCode * 8191 + ((isSetUserName()) ? 131071 : 524287);
    if (isSetUserName())
      hashCode = hashCode * 8191 + UserName.hashCode();

    hashCode = hashCode * 8191 + ((isSetPasswdMd5()) ? 131071 : 524287);
    if (isSetPasswdMd5())
      hashCode = hashCode * 8191 + PasswdMd5.hashCode();

    hashCode = hashCode * 8191 + ((isSetNickName()) ? 131071 : 524287);
    if (isSetNickName())
      hashCode = hashCode * 8191 + NickName.hashCode();

    hashCode = hashCode * 8191 + ((isSetRegisterDate()) ? 131071 : 524287);
    if (isSetRegisterDate())
      hashCode = hashCode * 8191 + RegisterDate.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(User other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetUid(), other.isSetUid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Uid, other.Uid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetUserName(), other.isSetUserName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.UserName, other.UserName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPasswdMd5(), other.isSetPasswdMd5());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPasswdMd5()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.PasswdMd5, other.PasswdMd5);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetNickName(), other.isSetNickName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNickName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.NickName, other.NickName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRegisterDate(), other.isSetRegisterDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRegisterDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.RegisterDate, other.RegisterDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("User(");
    boolean first = true;

    if (isSetUid()) {
      sb.append("Uid:");
      sb.append(this.Uid);
      first = false;
    }
    if (isSetUserName()) {
      if (!first) sb.append(", ");
      sb.append("UserName:");
      if (this.UserName == null) {
        sb.append("null");
      } else {
        sb.append(this.UserName);
      }
      first = false;
    }
    if (isSetPasswdMd5()) {
      if (!first) sb.append(", ");
      sb.append("PasswdMd5:");
      if (this.PasswdMd5 == null) {
        sb.append("null");
      } else {
        sb.append(this.PasswdMd5);
      }
      first = false;
    }
    if (isSetNickName()) {
      if (!first) sb.append(", ");
      sb.append("NickName:");
      if (this.NickName == null) {
        sb.append("null");
      } else {
        sb.append(this.NickName);
      }
      first = false;
    }
    if (isSetRegisterDate()) {
      if (!first) sb.append(", ");
      sb.append("RegisterDate:");
      if (this.RegisterDate == null) {
        sb.append("null");
      } else {
        sb.append(this.RegisterDate);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public UserStandardScheme getScheme() {
      return new UserStandardScheme();
    }
  }

  private static class UserStandardScheme extends org.apache.thrift.scheme.StandardScheme<User> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, User struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // UID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.Uid = iprot.readI64();
              struct.setUidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // USER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.UserName = iprot.readString();
              struct.setUserNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PASSWD_MD5
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.PasswdMd5 = iprot.readString();
              struct.setPasswdMd5IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // NICK_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.NickName = iprot.readString();
              struct.setNickNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // REGISTER_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.RegisterDate = iprot.readString();
              struct.setRegisterDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, User struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetUid()) {
        oprot.writeFieldBegin(UID_FIELD_DESC);
        oprot.writeI64(struct.Uid);
        oprot.writeFieldEnd();
      }
      if (struct.UserName != null) {
        if (struct.isSetUserName()) {
          oprot.writeFieldBegin(USER_NAME_FIELD_DESC);
          oprot.writeString(struct.UserName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.PasswdMd5 != null) {
        if (struct.isSetPasswdMd5()) {
          oprot.writeFieldBegin(PASSWD_MD5_FIELD_DESC);
          oprot.writeString(struct.PasswdMd5);
          oprot.writeFieldEnd();
        }
      }
      if (struct.NickName != null) {
        if (struct.isSetNickName()) {
          oprot.writeFieldBegin(NICK_NAME_FIELD_DESC);
          oprot.writeString(struct.NickName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.RegisterDate != null) {
        if (struct.isSetRegisterDate()) {
          oprot.writeFieldBegin(REGISTER_DATE_FIELD_DESC);
          oprot.writeString(struct.RegisterDate);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public UserTupleScheme getScheme() {
      return new UserTupleScheme();
    }
  }

  private static class UserTupleScheme extends org.apache.thrift.scheme.TupleScheme<User> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, User struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetUid()) {
        optionals.set(0);
      }
      if (struct.isSetUserName()) {
        optionals.set(1);
      }
      if (struct.isSetPasswdMd5()) {
        optionals.set(2);
      }
      if (struct.isSetNickName()) {
        optionals.set(3);
      }
      if (struct.isSetRegisterDate()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetUid()) {
        oprot.writeI64(struct.Uid);
      }
      if (struct.isSetUserName()) {
        oprot.writeString(struct.UserName);
      }
      if (struct.isSetPasswdMd5()) {
        oprot.writeString(struct.PasswdMd5);
      }
      if (struct.isSetNickName()) {
        oprot.writeString(struct.NickName);
      }
      if (struct.isSetRegisterDate()) {
        oprot.writeString(struct.RegisterDate);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, User struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.Uid = iprot.readI64();
        struct.setUidIsSet(true);
      }
      if (incoming.get(1)) {
        struct.UserName = iprot.readString();
        struct.setUserNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.PasswdMd5 = iprot.readString();
        struct.setPasswdMd5IsSet(true);
      }
      if (incoming.get(3)) {
        struct.NickName = iprot.readString();
        struct.setNickNameIsSet(true);
      }
      if (incoming.get(4)) {
        struct.RegisterDate = iprot.readString();
        struct.setRegisterDateIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

