# spring设置
spring:
  application:
    name: mim-netty
  main:
    allow-circular-references: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ss
    password: 1234
# 日志设置
logging:
  level:
    com.mdc.mim: info

# mim server配置
mim:
  server:
    # 服务端接收端口配置
    host: localhost
    port: 8080
    test:
      enabled: true # 启用压力测试

# nacos配置
nacos:
  discovery:
    server-addr: 127.0.0.1:8848
    username: nacos
    password: nacos
    auto-register: true
    register:
      groupName: MIM